export const ROUTES = {
  root: '/',
  dashboard: {
    root: '/dashboard',
    home: '/dashboard/home',
    employees: '/dashboard/employees',
    statistics: '/dashboard/statistics',
    'statistics-1': '/dashboard/statistics-1',
    'statistics-2': '/dashboard/statistics-2',
    'statistics-3': '/dashboard/statistics-3',
    'statistics-4': '/dashboard/statistics-4',
    'statistics-5': '/dashboard/statistics-5',
    shifts: '/dashboard/shifts',
    transactions: '/dashboard/transactions',
    library: '/dashboard/library',
    locations: '/dashboard/locations',
    'cash-out': '/dashboard/cash-out',
    statement: '/dashboard/statement',
    downloads: '/dashboard/downloads',
    history: '/dashboard/history',
    management: '/dashboard/management',
    tracking: '/dashboard/tracking',
    settings: '/dashboard/settings',
    dictionary: '/dashboard/dictionary',
    support: '/dashboard/support',
  },
} as const
