/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as DashboardLayoutRouteImport } from './pages/dashboard/layout'
import { Route as IndexRouteImport } from './pages/index'
import { Route as DashboardIndexRouteImport } from './pages/dashboard/index'
import { Route as DashboardTransactionsIndexRouteImport } from './pages/dashboard/transactions/index'
import { Route as DashboardTrackingIndexRouteImport } from './pages/dashboard/tracking/index'
import { Route as DashboardSupportIndexRouteImport } from './pages/dashboard/support/index'
import { Route as DashboardStatisticsIndexRouteImport } from './pages/dashboard/statistics/index'
import { Route as DashboardStatistics5IndexRouteImport } from './pages/dashboard/statistics-5/index'
import { Route as DashboardStatistics4IndexRouteImport } from './pages/dashboard/statistics-4/index'
import { Route as DashboardStatistics3IndexRouteImport } from './pages/dashboard/statistics-3/index'
import { Route as DashboardStatistics2IndexRouteImport } from './pages/dashboard/statistics-2/index'
import { Route as DashboardStatistics1IndexRouteImport } from './pages/dashboard/statistics-1/index'
import { Route as DashboardStatementIndexRouteImport } from './pages/dashboard/statement/index'
import { Route as DashboardShiftsIndexRouteImport } from './pages/dashboard/shifts/index'
import { Route as DashboardSettingsIndexRouteImport } from './pages/dashboard/settings/index'
import { Route as DashboardManagementIndexRouteImport } from './pages/dashboard/management/index'
import { Route as DashboardLocationsIndexRouteImport } from './pages/dashboard/locations/index'
import { Route as DashboardLibraryIndexRouteImport } from './pages/dashboard/library/index'
import { Route as DashboardHomeIndexRouteImport } from './pages/dashboard/home/index'
import { Route as DashboardHistoryIndexRouteImport } from './pages/dashboard/history/index'
import { Route as DashboardEmployeesIndexRouteImport } from './pages/dashboard/employees/index'
import { Route as DashboardDownloadsIndexRouteImport } from './pages/dashboard/downloads/index'
import { Route as DashboardDictionaryIndexRouteImport } from './pages/dashboard/dictionary/index'
import { Route as DashboardCashOutIndexRouteImport } from './pages/dashboard/cash-out/index'
import { Route as AuthSignInIndexRouteImport } from './pages/auth/sign-in/index'

const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardTransactionsIndexRoute =
  DashboardTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardTrackingIndexRoute = DashboardTrackingIndexRouteImport.update({
  id: '/tracking/',
  path: '/tracking/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardSupportIndexRoute = DashboardSupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardStatisticsIndexRoute =
  DashboardStatisticsIndexRouteImport.update({
    id: '/statistics/',
    path: '/statistics/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardStatistics5IndexRoute =
  DashboardStatistics5IndexRouteImport.update({
    id: '/statistics-5/',
    path: '/statistics-5/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardStatistics4IndexRoute =
  DashboardStatistics4IndexRouteImport.update({
    id: '/statistics-4/',
    path: '/statistics-4/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardStatistics3IndexRoute =
  DashboardStatistics3IndexRouteImport.update({
    id: '/statistics-3/',
    path: '/statistics-3/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardStatistics2IndexRoute =
  DashboardStatistics2IndexRouteImport.update({
    id: '/statistics-2/',
    path: '/statistics-2/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardStatistics1IndexRoute =
  DashboardStatistics1IndexRouteImport.update({
    id: '/statistics-1/',
    path: '/statistics-1/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardStatementIndexRoute = DashboardStatementIndexRouteImport.update({
  id: '/statement/',
  path: '/statement/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardShiftsIndexRoute = DashboardShiftsIndexRouteImport.update({
  id: '/shifts/',
  path: '/shifts/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardManagementIndexRoute =
  DashboardManagementIndexRouteImport.update({
    id: '/management/',
    path: '/management/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLocationsIndexRoute = DashboardLocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLibraryIndexRoute = DashboardLibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardHomeIndexRoute = DashboardHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardHistoryIndexRoute = DashboardHistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardEmployeesIndexRoute = DashboardEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardDownloadsIndexRoute = DashboardDownloadsIndexRouteImport.update({
  id: '/downloads/',
  path: '/downloads/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardDictionaryIndexRoute =
  DashboardDictionaryIndexRouteImport.update({
    id: '/dictionary/',
    path: '/dictionary/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardCashOutIndexRoute = DashboardCashOutIndexRouteImport.update({
  id: '/cash-out/',
  path: '/cash-out/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/auth/sign-in/',
  path: '/auth/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
  '/dashboard/cash-out': typeof DashboardCashOutIndexRoute
  '/dashboard/dictionary': typeof DashboardDictionaryIndexRoute
  '/dashboard/downloads': typeof DashboardDownloadsIndexRoute
  '/dashboard/employees': typeof DashboardEmployeesIndexRoute
  '/dashboard/history': typeof DashboardHistoryIndexRoute
  '/dashboard/home': typeof DashboardHomeIndexRoute
  '/dashboard/library': typeof DashboardLibraryIndexRoute
  '/dashboard/locations': typeof DashboardLocationsIndexRoute
  '/dashboard/management': typeof DashboardManagementIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/shifts': typeof DashboardShiftsIndexRoute
  '/dashboard/statement': typeof DashboardStatementIndexRoute
  '/dashboard/statistics-1': typeof DashboardStatistics1IndexRoute
  '/dashboard/statistics-2': typeof DashboardStatistics2IndexRoute
  '/dashboard/statistics-3': typeof DashboardStatistics3IndexRoute
  '/dashboard/statistics-4': typeof DashboardStatistics4IndexRoute
  '/dashboard/statistics-5': typeof DashboardStatistics5IndexRoute
  '/dashboard/statistics': typeof DashboardStatisticsIndexRoute
  '/dashboard/support': typeof DashboardSupportIndexRoute
  '/dashboard/tracking': typeof DashboardTrackingIndexRoute
  '/dashboard/transactions': typeof DashboardTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
  '/dashboard/cash-out': typeof DashboardCashOutIndexRoute
  '/dashboard/dictionary': typeof DashboardDictionaryIndexRoute
  '/dashboard/downloads': typeof DashboardDownloadsIndexRoute
  '/dashboard/employees': typeof DashboardEmployeesIndexRoute
  '/dashboard/history': typeof DashboardHistoryIndexRoute
  '/dashboard/home': typeof DashboardHomeIndexRoute
  '/dashboard/library': typeof DashboardLibraryIndexRoute
  '/dashboard/locations': typeof DashboardLocationsIndexRoute
  '/dashboard/management': typeof DashboardManagementIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/shifts': typeof DashboardShiftsIndexRoute
  '/dashboard/statement': typeof DashboardStatementIndexRoute
  '/dashboard/statistics-1': typeof DashboardStatistics1IndexRoute
  '/dashboard/statistics-2': typeof DashboardStatistics2IndexRoute
  '/dashboard/statistics-3': typeof DashboardStatistics3IndexRoute
  '/dashboard/statistics-4': typeof DashboardStatistics4IndexRoute
  '/dashboard/statistics-5': typeof DashboardStatistics5IndexRoute
  '/dashboard/statistics': typeof DashboardStatisticsIndexRoute
  '/dashboard/support': typeof DashboardSupportIndexRoute
  '/dashboard/tracking': typeof DashboardTrackingIndexRoute
  '/dashboard/transactions': typeof DashboardTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/dashboard/cash-out/': typeof DashboardCashOutIndexRoute
  '/dashboard/dictionary/': typeof DashboardDictionaryIndexRoute
  '/dashboard/downloads/': typeof DashboardDownloadsIndexRoute
  '/dashboard/employees/': typeof DashboardEmployeesIndexRoute
  '/dashboard/history/': typeof DashboardHistoryIndexRoute
  '/dashboard/home/': typeof DashboardHomeIndexRoute
  '/dashboard/library/': typeof DashboardLibraryIndexRoute
  '/dashboard/locations/': typeof DashboardLocationsIndexRoute
  '/dashboard/management/': typeof DashboardManagementIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/shifts/': typeof DashboardShiftsIndexRoute
  '/dashboard/statement/': typeof DashboardStatementIndexRoute
  '/dashboard/statistics-1/': typeof DashboardStatistics1IndexRoute
  '/dashboard/statistics-2/': typeof DashboardStatistics2IndexRoute
  '/dashboard/statistics-3/': typeof DashboardStatistics3IndexRoute
  '/dashboard/statistics-4/': typeof DashboardStatistics4IndexRoute
  '/dashboard/statistics-5/': typeof DashboardStatistics5IndexRoute
  '/dashboard/statistics/': typeof DashboardStatisticsIndexRoute
  '/dashboard/support/': typeof DashboardSupportIndexRoute
  '/dashboard/tracking/': typeof DashboardTrackingIndexRoute
  '/dashboard/transactions/': typeof DashboardTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/auth/sign-in'
    | '/dashboard/cash-out'
    | '/dashboard/dictionary'
    | '/dashboard/downloads'
    | '/dashboard/employees'
    | '/dashboard/history'
    | '/dashboard/home'
    | '/dashboard/library'
    | '/dashboard/locations'
    | '/dashboard/management'
    | '/dashboard/settings'
    | '/dashboard/shifts'
    | '/dashboard/statement'
    | '/dashboard/statistics-1'
    | '/dashboard/statistics-2'
    | '/dashboard/statistics-3'
    | '/dashboard/statistics-4'
    | '/dashboard/statistics-5'
    | '/dashboard/statistics'
    | '/dashboard/support'
    | '/dashboard/tracking'
    | '/dashboard/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/auth/sign-in'
    | '/dashboard/cash-out'
    | '/dashboard/dictionary'
    | '/dashboard/downloads'
    | '/dashboard/employees'
    | '/dashboard/history'
    | '/dashboard/home'
    | '/dashboard/library'
    | '/dashboard/locations'
    | '/dashboard/management'
    | '/dashboard/settings'
    | '/dashboard/shifts'
    | '/dashboard/statement'
    | '/dashboard/statistics-1'
    | '/dashboard/statistics-2'
    | '/dashboard/statistics-3'
    | '/dashboard/statistics-4'
    | '/dashboard/statistics-5'
    | '/dashboard/statistics'
    | '/dashboard/support'
    | '/dashboard/tracking'
    | '/dashboard/transactions'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/auth/sign-in/'
    | '/dashboard/cash-out/'
    | '/dashboard/dictionary/'
    | '/dashboard/downloads/'
    | '/dashboard/employees/'
    | '/dashboard/history/'
    | '/dashboard/home/'
    | '/dashboard/library/'
    | '/dashboard/locations/'
    | '/dashboard/management/'
    | '/dashboard/settings/'
    | '/dashboard/shifts/'
    | '/dashboard/statement/'
    | '/dashboard/statistics-1/'
    | '/dashboard/statistics-2/'
    | '/dashboard/statistics-3/'
    | '/dashboard/statistics-4/'
    | '/dashboard/statistics-5/'
    | '/dashboard/statistics/'
    | '/dashboard/support/'
    | '/dashboard/tracking/'
    | '/dashboard/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/transactions/': {
      id: '/dashboard/transactions/'
      path: '/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof DashboardTransactionsIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/tracking/': {
      id: '/dashboard/tracking/'
      path: '/tracking'
      fullPath: '/dashboard/tracking'
      preLoaderRoute: typeof DashboardTrackingIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/support/': {
      id: '/dashboard/support/'
      path: '/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof DashboardSupportIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/statistics/': {
      id: '/dashboard/statistics/'
      path: '/statistics'
      fullPath: '/dashboard/statistics'
      preLoaderRoute: typeof DashboardStatisticsIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/statistics-5/': {
      id: '/dashboard/statistics-5/'
      path: '/statistics-5'
      fullPath: '/dashboard/statistics-5'
      preLoaderRoute: typeof DashboardStatistics5IndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/statistics-4/': {
      id: '/dashboard/statistics-4/'
      path: '/statistics-4'
      fullPath: '/dashboard/statistics-4'
      preLoaderRoute: typeof DashboardStatistics4IndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/statistics-3/': {
      id: '/dashboard/statistics-3/'
      path: '/statistics-3'
      fullPath: '/dashboard/statistics-3'
      preLoaderRoute: typeof DashboardStatistics3IndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/statistics-2/': {
      id: '/dashboard/statistics-2/'
      path: '/statistics-2'
      fullPath: '/dashboard/statistics-2'
      preLoaderRoute: typeof DashboardStatistics2IndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/statistics-1/': {
      id: '/dashboard/statistics-1/'
      path: '/statistics-1'
      fullPath: '/dashboard/statistics-1'
      preLoaderRoute: typeof DashboardStatistics1IndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/statement/': {
      id: '/dashboard/statement/'
      path: '/statement'
      fullPath: '/dashboard/statement'
      preLoaderRoute: typeof DashboardStatementIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/shifts/': {
      id: '/dashboard/shifts/'
      path: '/shifts'
      fullPath: '/dashboard/shifts'
      preLoaderRoute: typeof DashboardShiftsIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/management/': {
      id: '/dashboard/management/'
      path: '/management'
      fullPath: '/dashboard/management'
      preLoaderRoute: typeof DashboardManagementIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/locations/': {
      id: '/dashboard/locations/'
      path: '/locations'
      fullPath: '/dashboard/locations'
      preLoaderRoute: typeof DashboardLocationsIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/library/': {
      id: '/dashboard/library/'
      path: '/library'
      fullPath: '/dashboard/library'
      preLoaderRoute: typeof DashboardLibraryIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/home/': {
      id: '/dashboard/home/'
      path: '/home'
      fullPath: '/dashboard/home'
      preLoaderRoute: typeof DashboardHomeIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/history/': {
      id: '/dashboard/history/'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/employees/': {
      id: '/dashboard/employees/'
      path: '/employees'
      fullPath: '/dashboard/employees'
      preLoaderRoute: typeof DashboardEmployeesIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/downloads/': {
      id: '/dashboard/downloads/'
      path: '/downloads'
      fullPath: '/dashboard/downloads'
      preLoaderRoute: typeof DashboardDownloadsIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/dictionary/': {
      id: '/dashboard/dictionary/'
      path: '/dictionary'
      fullPath: '/dashboard/dictionary'
      preLoaderRoute: typeof DashboardDictionaryIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/cash-out/': {
      id: '/dashboard/cash-out/'
      path: '/cash-out'
      fullPath: '/dashboard/cash-out'
      preLoaderRoute: typeof DashboardCashOutIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/auth/sign-in/': {
      id: '/auth/sign-in/'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardLayoutRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCashOutIndexRoute: typeof DashboardCashOutIndexRoute
  DashboardDictionaryIndexRoute: typeof DashboardDictionaryIndexRoute
  DashboardDownloadsIndexRoute: typeof DashboardDownloadsIndexRoute
  DashboardEmployeesIndexRoute: typeof DashboardEmployeesIndexRoute
  DashboardHistoryIndexRoute: typeof DashboardHistoryIndexRoute
  DashboardHomeIndexRoute: typeof DashboardHomeIndexRoute
  DashboardLibraryIndexRoute: typeof DashboardLibraryIndexRoute
  DashboardLocationsIndexRoute: typeof DashboardLocationsIndexRoute
  DashboardManagementIndexRoute: typeof DashboardManagementIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardShiftsIndexRoute: typeof DashboardShiftsIndexRoute
  DashboardStatementIndexRoute: typeof DashboardStatementIndexRoute
  DashboardStatistics1IndexRoute: typeof DashboardStatistics1IndexRoute
  DashboardStatistics2IndexRoute: typeof DashboardStatistics2IndexRoute
  DashboardStatistics3IndexRoute: typeof DashboardStatistics3IndexRoute
  DashboardStatistics4IndexRoute: typeof DashboardStatistics4IndexRoute
  DashboardStatistics5IndexRoute: typeof DashboardStatistics5IndexRoute
  DashboardStatisticsIndexRoute: typeof DashboardStatisticsIndexRoute
  DashboardSupportIndexRoute: typeof DashboardSupportIndexRoute
  DashboardTrackingIndexRoute: typeof DashboardTrackingIndexRoute
  DashboardTransactionsIndexRoute: typeof DashboardTransactionsIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCashOutIndexRoute: DashboardCashOutIndexRoute,
  DashboardDictionaryIndexRoute: DashboardDictionaryIndexRoute,
  DashboardDownloadsIndexRoute: DashboardDownloadsIndexRoute,
  DashboardEmployeesIndexRoute: DashboardEmployeesIndexRoute,
  DashboardHistoryIndexRoute: DashboardHistoryIndexRoute,
  DashboardHomeIndexRoute: DashboardHomeIndexRoute,
  DashboardLibraryIndexRoute: DashboardLibraryIndexRoute,
  DashboardLocationsIndexRoute: DashboardLocationsIndexRoute,
  DashboardManagementIndexRoute: DashboardManagementIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardShiftsIndexRoute: DashboardShiftsIndexRoute,
  DashboardStatementIndexRoute: DashboardStatementIndexRoute,
  DashboardStatistics1IndexRoute: DashboardStatistics1IndexRoute,
  DashboardStatistics2IndexRoute: DashboardStatistics2IndexRoute,
  DashboardStatistics3IndexRoute: DashboardStatistics3IndexRoute,
  DashboardStatistics4IndexRoute: DashboardStatistics4IndexRoute,
  DashboardStatistics5IndexRoute: DashboardStatistics5IndexRoute,
  DashboardStatisticsIndexRoute: DashboardStatisticsIndexRoute,
  DashboardSupportIndexRoute: DashboardSupportIndexRoute,
  DashboardTrackingIndexRoute: DashboardTrackingIndexRoute,
  DashboardTransactionsIndexRoute: DashboardTransactionsIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
